version: '3.8'

services:
  django:
    image: musfiqus/portfolio_server:${IMAGE_CLASSIFIER_BACKEND_TAG}
    env_file:
      - .env
    volumes:
      - ./backend:/app
    ports:
      - "${DJANGO_HOST_PORT}:${DJANGO_CONTAINER_PORT}"
    depends_on:
      - postgres
      - redis
    links:
      - postgres

  react:
    image: musfiqus/portfolio_server:${IMAGE_CLASSIFIER_FRONTEND_TAG}
    ports:
      - "${REACT_HOST_PORT}:${REACT_CONTAINER_PORT}"
    depends_on:
      - django
    volumes:
      - /app/node_modules
      - ./frontend:/app
    env_file:
      - .env
    stdin_open: true
    tty: true

  postgres:
    image: postgres:latest
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "${POSTGRES_HOST_PORT}:${POSTGRES_CONTAINER_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    command: --port ${REDIS_CONTAINER_PORT} 
    ports:
      - "${REDIS_HOST_PORT}:${REDIS_CONTAINER_PORT}"

volumes:
  postgres_data: