version: '3.8'

services:
  django:
    build:
      context: ./backend
    container_name: django_app
    command: ["./start.sh"]
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=True
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=musfiqus@gmail.com
      - DJANGO_SUPERUSER_PASSWORD=admin1234
      - DATABASE_ENGINE=django.db.backends.postgresql
      - DATABASE_NAME=image_db
      - DATABASE_USER=db_admin
      - DATABASE_PASSWORD=db7654
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
    depends_on:
      - postgres
    links:
      - postgres

  react:
    build:
      context: ./frontend
    container_name: react_app
    command: sh -c "yarn install && yarn dev"
    ports:
      - "3000:3000"
    depends_on:
      - django
    volumes:
      - /app/node_modules
      - ./frontend:/app
    environment:
      - CI=false
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=false
      - WDS_SOCKET_PORT=3000 # The mapped port on the host machine
      - REACT_APP_BACKEND_URL=http://localhost:8000
    stdin_open: true
    tty: true

  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: db_admin
      POSTGRES_PASSWORD: db7654
      POSTGRES_DB: image_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
