version: '3.8'

services:
  django:
    build:
      context: ./backend
    container_name: django_app
    command: ["./start.sh"]
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=True
      - DEBUG_SECRET_KEY=django-insecure-40(v3$ax#2@e6&up5@did1!27b0!q2c(vihu4n4qj!&e+v+35*
      - DEBUG_FRONTEND_URL=http://localhost:3000
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@site.com
      - DJANGO_SUPERUSER_PASSWORD=admin1234
      - DATABASE_ENGINE=django.db.backends.postgresql
      - DATABASE_NAME=image_db
      - DATABASE_USER=db_admin
      - DATABASE_PASSWORD=db7654
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DEFAULT_CLASSIFICATION_MODEL=efficientnetv2_rw_m.agc_in1k
      - DEFAULT_LABELS_URL=https://raw.githubusercontent.com/pytorch/hub/master/imagenet_classes.txt
      - REDIS_URL=redis://redis:6379

    depends_on:
      - postgres
      - redis
    links:
      - postgres

  react:
    build:
      context: ./frontend
    container_name: react_app
    command: sh -c "yarn install && yarn dev"
    ports:
      - "3000:3000"
    depends_on:
      - django
    volumes:
      - /app/node_modules
      - ./frontend:/app
    environment:
      - CI=false
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=false
      - WDS_SOCKET_PORT=3000 # The mapped port on the host machine
      - REACT_APP_BACKEND_URL=http://localhost:8000
    stdin_open: true
    tty: true

  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: db_admin
      POSTGRES_PASSWORD: db7654
      POSTGRES_DB: image_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  celery:
    build: ./backend
    command: celery -A core worker --loglevel=info
    volumes:
      - ./backend:/app
    depends_on:
      - django
      - redis
    environment:
      - DEBUG=True
      - DEBUG_SECRET_KEY=django-insecure-40(v3$ax#2@e6&up5@did1!27b0!q2c(vihu4n4qj!&e+v+35*
      - DEBUG_FRONTEND_URL=http://localhost:3000
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@site.com
      - DJANGO_SUPERUSER_PASSWORD=admin1234
      - DATABASE_ENGINE=django.db.backends.postgresql
      - DATABASE_NAME=image_db
      - DATABASE_USER=db_admin
      - DATABASE_PASSWORD=db7654
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DEFAULT_CLASSIFICATION_MODEL=efficientnetv2_rw_m.agc_in1k
      - DEFAULT_LABELS_URL=https://raw.githubusercontent.com/pytorch/hub/master/imagenet_classes.txt
      - REDIS_URL=redis://redis:6379


  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  postgres_data:
