# Generated by Django 4.2.3 on 2023-07-27 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0003_alter_classificationmodel_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageclassification',
            name='in_queue',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='imageclassification',
            name='classification_model',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='imageclassification',
            name='labels_url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='imageclassification',
            name='predictions',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
