# Generated by Django 4.2.3 on 2023-07-28 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0004_imageclassification_in_queue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageclassification',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='imageclassification',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
